#!/bin/bash

set -e

cat <<EOF | redis-cli -h ${REDIS_HOST} -a ${REDIS_PASSWORD}
set foo 100
incr foo
append foo xxx
EOF

if [[ $(redis-cli -h ${REDIS_HOST} -a ${REDIS_PASSWORD} get foo) != "101xxx" ]]; then
  exit 1
fi
