#!/bin/bash

set -e

# setup wordpress
wp --allow-root --path=/hab/svc/wordpress/data/ core install  --title="WP-CLI" --admin_user=wpcli --admin_password=wpcli --admin_email=info@wp-cli.org --url=localhost

# generate 100 posts with dummy data
wp --allow-root --path=/hab/svc/wordpress/data/ post generate

# get the details of the 10th post
wp --allow-root --path=/hab/svc/wordpress/data/ post get 10
