#!/bin/bash

source {{pkg.svc_config_path}}/environment.sh

echo "Checking if shield-daemon is available"

curl "${SHIELD_ENDPOINT}/v1/ping"
if [[ $? != 0 ]]; then
  echo "Shield is not available"
  exit 1
fi

# This is to satisfy the hard coded path in the postgresql plugin
rm /var/vcap/packages/postgres-9.4/bin
mkdir -p /var/vcap/packages/postgres-9.4
ln -s {{pkgPathFor "starkandwayne/postgresql"}}/bin /var/vcap/packages/postgres-9.4/bin

# This is a hack to setup a cert path that golang will find (https://golang.org/src/crypto/x509/root_linux.go)
# Also currently the {{pkgPathFor "core/cacerts"}} helper invocation will initially fail (https://github.com/habitat-sh/habitat/issues/1904)
# This can be ignored... eventually the hook will render correctly and things will work!
rm /etc/ssl/ca-bundle.pem
mkdir -p /etc/ssl
ln -s {{pkgPathFor "core/cacerts"}}/ssl/certs/cacert.pem /etc/ssl/ca-bundle.pem
