#!/bin/bash

set -e

source {{pkg.svc_config_path}}/environment.sh

echo "Checking if shield-daemon is available"

curl "${SHIELD_ENDPOINT}/v1/ping"

# this is to satisfy the hard coded path in the postgresql plugin
mkdir -p /var/vcap/packages/postgres-9.4
ln -s $(dirname $(which psql)) /var/vcap/packages/postgres-9.4/bin
