#!/bin/bash

exec 2>&1

echo "Attempting to set up SSH public keys"
AUTHKEYS={{pkg.svc_var_path}}/authorized_keys

{{~#with bind.daemon.[0]}}
curl -Lks "http://{{sys.ip}}:{{cfg.port}}v1/meta/pubkey" -m 20 >> $AUTHKEYS{{~/with}}

exec shield-agent -c {{pkg.svc_config_path}}/shield-agent.conf --log-level {{cfg.log_level}} 2>&1
