#!/bin/bash

set -ex

outdir=${PWD}/${OUT}

cd ${PACKAGE_CONTEXT}

cat <<EOF | hab origin key import
${HAB_ORIGIN_KEY}
EOF

hab pkg build .

mv results/* ${outdir}
ls ${outdir}/${HAB_ORIGIN}* > ${outdir}/pkg_name

dockerd >/tmp/docker.log 2>&1 &
until docker info >/dev/null 2>&1; do
  echo waiting for docker to come up...
  sleep 1
done

hab pkg export docker ${HAB_ORIGIN}/${PLAN_NAME}

docker_tag=$(docker images | grep ${HAB_ORIGIN} | grep -v 'latest' | awk '{print $2}')
docker save -o ${outdir}/${HAB_ORIGIN}-${PLAN_NAME}-docker.tar ${HAB_ORIGIN}/${PLAN_NAME}:${docker_tag}

echo ${docker_tag} > ${outdir}/docker_tag
