#!/bin/bash

echo 2>&1

echo COPY "ERLANG COOKIE!"
cp {{pkg.svc_config_path}}/.erlang.cookie  {{pkg.svc_var_path}}
chmod 600 {{pkg.svc_var_path}}/.erlang.cookie

source "{{pkg.svc_config_path}}/env"

{{#if cfg.rabbitmq.management.enabled}}
echo "Enabling management console"
rabbitmq-plugins --offline enable rabbitmq_management
{{else}}
echo "Disabling management console"
rabbitmq-plugins --offline disable rabbitmq_management
{{/if}}
