#!/bin/bash

cp {{pkg.svc_config_path}}/.erlang.cookie  {{pkg.svc_var_path}}
chmod 600 {{pkg.svc_var_path}}/.erlang.cookie

source "{{pkg.svc_config_path}}/env"

# https://www.youtube.com/watch?v=wGhQ2BDt4VE
kill_rabbit() {
  rabbitmqctl stop
  exit
}

trap "kill_rabbit" INT TERM HUP ABRT QUIT

# We do NOT call exec here, as we trap signals and kill rabbit in this script
rabbitmq-server 2>&1
