#!/bin/bash

set -e

# delmo is not fast enough to pickup the messages
sleep 8

RET=1
curl -s -u admin:admin http://standalone:15672/api/nodes | sed 's/^.\(.*\).$/\1/' | sed 's/,{"cluster_links/{"cluster_links/g' | jq -r '.name' | while read OUTPUT; do
      curl --fail -u admin:admin http://standalone:15672/api/healthchecks/node/$OUTPUT
      echo $OUTPUT
      RET=$?
  done || exit $RET
