#!/bin/bash

write_env_var() {
  echo "$1" > "{{pkg.svc_config_path}}/env/$2"
}

write_env_var {{cfg.wale_s3_prefix}} WALE_S3_PREFIX
write_env_var {{cfg.aws_access_key_id}} AWS_ACCESS_KEY_ID
write_env_var {{cfg.aws_secret_access_key}} AWS_SECRET_ACCESS_KEY
write_env_var {{cfg.aws_region}} AWS_REGION

while true; do
  envdir {{pkg.svc_config_path}}/env wal-e backup-push {{cfg.pg_data_dir}}
  sleep {{cfg.backup_interval}}
done
