#!/bin/sh

exec 2>&1

chown -R hab:hab {{pkg.svc_var_path}}

if [[ ! -f "{{pkg.svc_data_path}}/PG_VERSION" ]]; then
  echo " Database does not exist, creating with 'initdb'"
  initdb -U {{cfg.superuser.name}} \
    -E utf8 \
    -D {{pkg.svc_data_path}} \
    --pwfile {{pkg.svc_config_path}}/pwfile \
    --locale en_US.UTF-8
fi
