#!/bin/bash

if hab sup status | grep wal-e; then
  hab service unload starkandwayne/wal-e
fi

{{ #unless svc.me.follower }}
{{ #if cfg.wal-e.enable }}
echo "Starting wal-e to perform regular backups"
mkdir -p /hab/svc/wal-e/
cp {{pkg.svc_config_path}}/wal-e.toml /hab/svc/wal-e/user.toml
hab service load starkandwayne/wal-e --group {{svc.group}}
{{ /if }}
{{ /unless }}
