#!/bin/sh

source {{pkg.svc_config_path}}/functions.sh

stop_wale_service

{{ #unless svc.me.follower }}
if [ -f {{pkg.svc_data_path}}/recovery.conf ]; then
  echo "Promoting database"
  until PGPASSWORD={{cfg.superuser.password}} pg_isready -U {{cfg.superuser.name}} -h localhost; do
    echo "Waiting for database to start"
    sleep 1
  done

  pg_ctl promote -D {{pkg.svc_data_path}}
fi

{{ #if cfg.wal-e.enable }}
start_wale_service
{{ /if }}
{{~/unless}}

