#!/bin/sh

{{#unless svc.me.follower ~}}
if [ -f {{pkg.svc_data_path}}/recovery.conf ]; then
  echo "Promoting database"
  until PGPASSWORD={{cfg.superuser.password}} pg_isready -U {{cfg.superuser.name}} -h localhost; do
    echo "Waiting for database to start"
    sleep 1
  done

  pg_ctl promote -D {{pkg.svc_data_path}}
fi
{{~/unless}}

