#!/bin/sh

set -e

echo "Starting PostgreSQL"

export PGDATA={{pkg.svc_data_path}}

{{#if svc.me.follower ~}}
cp {{pkg.svc_config_path}}/recovery.conf {{pkg.svc_data_path}}/
{{~/if}}

exec 2>&1
exec postmaster \
     -c config_file={{pkg.svc_config_path}}/postgresql.conf
