#!/bin/bash

source /scripts/lib/functions postgres

rc=0
cat <<EOF
########   #######   ######  ########  ######   ########  ########  ######
##     ## ##     ## ##    ##    ##    ##    ##  ##     ## ##       ##    ##
##     ## ##     ## ##          ##    ##        ##     ## ##       ##
########  ##     ##  ######     ##    ##   #### ########  ######    ######
##        ##     ##       ##    ##    ##    ##  ##   ##   ##             ##
##        ##     ## ##    ##    ##    ##    ##  ##    ##  ##       ##    ##
##         #######   ######     ##     ######   ##     ## ########  ######
EOF

echo "> Postgres - All Databases"
echo ">> setting up test data"
psql postgres <$ROOT/init.sql
psql db1 -c 'SELECT * FROM t_vals ORDER BY ID ASC' >$TMP/db1.dat
psql db2 -c 'SELECT * FROM t_keys ORDER BY ID ASC' >$TMP/db2.dat
echo "   db1.t_vals contains:"
sed -e 's/^/    /' <$TMP/db1.dat
echo
echo "   db2.t_keys contains:"
sed -e 's/^/    /' <$TMP/db2.dat
echo

echo ">> configuring SHIELD"
shield create-target <<EOF | jq -r .
{
  "name"     : "postgres-all",
  "summary"  : "Postgres All Databases",
  "plugin"   : "postgres",
  "endpoint" : "{\"pg_host\":\"${PGHOST}\",\"pg_user\":\"${PGUSER}\",\"pg_password\":\"${PGPASSWORD}\"}",
  "agent"    : "$AGENT_ENDPOINT:5444"
}
EOF
shield create-job <<EOF | jq -r .
{
  "name"      : "postgres-all-daily",
  "summary"   : "Postgres All Databases",
  "paused"    : true,
  "retention" : "$RETENTION_UUID",
  "schedule"  : "$SCHEDULE_UUID",
  "store"     : "$STORE_UUID",
  "target"    : "$(shield target postgres-all | jq -r '.uuid')"
}
EOF
echo

echo ">> running backup job"
wait_for_task $(shield run $(shield job postgres-all-daily | jq -r '.uuid') | jq -r '.task_uuid')
echo

exit $rc;
