#!/bin/bash

set -e

export PGHOST="${1}"
if [[ ${PGHOST} == 'cluster' ]]; then
  export PGHOST=$(curl standalone:9631/census \
    | jq -r '.censuses["postgresql.cluster"].population [] | select(.leader == true) | .sys.ip')
  echo "Leader is ${PGHOST}"
fi

test_table="tests"
value="test-value"

psql <<EOF
DROP TABLE IF EXISTS ${test_table};
CREATE TABLE ${test_table}(value text);
INSERT INTO ${test_table} VALUES ('${value}');
EOF

psql -c "SELECT value FROM ${test_table};" | grep "${value}" || {
  echo Could not store and retrieve value in cluster!
    exit 1
  }
