#!/bin/bash

set -e

export PGHOST="${1}"
if [[ ${PGHOST} == 'cluster' ]]; then
  leader_id=$(curl -s standalone:9631/census | jq -r '.census_groups["postgresql.cluster"].leader_id')
  export PGHOST=$(curl -s standalone:9631/census \
    | jq --arg leader_id ${leader_id} -r '.census_groups["postgresql.cluster"].population[$leader_id].sys.ip')
  echo "Leader is ${PGHOST}"
fi

test_table="${2}"
value="${3}"

echo "Persisting value '${value}' in table '${test_table}'"

psql <<EOF
DROP TABLE IF EXISTS ${test_table};
CREATE TABLE ${test_table}(value text);
INSERT INTO ${test_table} VALUES ('${value}');
EOF

psql -c "SELECT value FROM ${test_table};" | grep "${value}" || {
  echo Could not store and retrieve value in cluster!
    exit 1
  }

psql -c "select pg_switch_xlog();"

