#!/bin/bash

echo "Executing shield post run hook"
if hab sup status | grep shield-proxy; then
  hab svc unload starkandwayne/shield-proxy
fi

echo "Starting shield-proxy"
mkdir -p /hab/svc/shield-proxy/
cp {{pkg.svc_config_path}}/shield-proxy.toml /hab/svc/shield-proxy/user.toml
hab svc load starkandwayne/shield-proxy --group {{svc.group}} --force
