#!/bin/bash -xe

exec 2>&1

##Helps identify config
cat {{pkg.svc_config_path}}/basic_config.json

exec consul agent -server -config-file={{pkg.svc_config_path}}/agent.json --node-id "$(cat {{pkg.svc_var_path}}/NODE_UUID)"
