#!/usr/bin/env bash

if [[ "${1}" == 'cluster' ]]; then
  echo "Finding cluster leader"
  export STANDALONE_HOST=$(curl -s standalone:9631/census \
    | jq -r '.censuses["postgresql.cluster"].population [] | select(.leader == true) | .sys.ip')
  if [[ "${STANDALONE_HOST}" == "" ]]; then
    echo "No leader currently elected"
    exit 1
  fi
  echo "Leader is ${STANDALONE_HOST}"
fi

curl -s -o /dev/null -w '%{http_code}\n' "${STANDALONE_HOST}"
