#!/bin/bash

leader=`curl -sL https://${STANDALONE_HOST}:${CONSUL_PORT}/v1/status/leader`
if [ ${leader} == '""' ]; then
  echo "leader is unset: ${leader}";
  exit 0
else
  echo "leader is set to '${leader}'";
  exit 1
fi
