#!/bin/bash

if [[ "${1}" == 'cluster' ]]; then
  consul_host=${CLUSTER_HOST}
  echo "Consul cluster address set to ${consul_host}:${CONSUL_PORT}"
else
  consul_host=${STANDALONE_HOST}
  echo "Consul standalone address set to ${consul_host}:${CONSUL_PORT}"
fi

echo "Running: curl -s -X PUT ${consul_host}:${CONSUL_PORT}/v1/kv/moo -d'rar'"
curl -s -X PUT ${consul_host}:${CONSUL_PORT}/v1/kv/moo -d'rar'

echo "Running: curl $consul_host:${CONSUL_PORT}/v1/kv/moo"
moovalue=`curl -s $consul_host:${CONSUL_PORT}/v1/kv/moo | jq -r '.Value' | base64 -d`
if [ $moovalue == 'rar' ]; then exit 0; fi

exit 1
