#!/bin/bash

if [[ "${1}" == 'cluster' ]]; then
  consul_host=${CLUSTER_HOST}
  echo "Consul cluster address set to ${consul_host}:${CONSUL_PORT}"
else
  consul_host=${STANDALONE_HOST}
  echo "Consul standalone address set to ${consul_host}:${CONSUL_PORT}"
fi

# Put a value into Consul
echo "Running: curl -k -sL -X PUT https://${consul_host}:${CONSUL_PORT}/v1/kv/moo -d'rar'"
echo `curl -k -s -X PUT https://${consul_host}:${CONSUL_PORT}/v1/kv/moo -d'rar'`

# Grab the value from Consul
# echo "Running: curl $consul_host:${CONSUL_PORT}/v1/kv/moo"
echo `curl -k -sL https://$consul_host:${CONSUL_PORT}/v1/kv/moo`

moovalue=`curl -k -sL https://$consul_host:${CONSUL_PORT}/v1/kv/moo | jq '.[0].Value' | base64 -d`
if [ $moovalue == 'rar' ]; then exit 0; fi

exit 1
